#!/bin/bash

clear

echo "##########################"
echo "            N             "
echo "##########################" 
./nanotekspice 4011_nand.nts < nandin.txt
echo ""

echo "##########################"
echo "            S             "
echo "##########################" 
./nanotekspice 4011_nandS.nts < nandinS.txt
echo ""

echo "##########################"
echo "            U             "
echo "##########################" 
./nanotekspice 4011_nandU.nts < nandinU.txt
echo ""
