#!/bin/bash

g++ and.cpp
./a.out
clear

echo "##########################"
echo "            1             "
echo "##########################" 
./nanotekspice and.nts < and1.txt
echo ""

echo "##########################"
echo "            2             "
echo "##########################" 
./nanotekspice and.nts < and2.txt
echo ""

echo "##########################"
echo "            3             "
echo "##########################" 
./nanotekspice and.nts < and3.txt
echo ""

echo "##########################"
echo "            4             "
echo "##########################" 
./nanotekspice and.nts < and4.txt
echo ""

echo "##########################"
echo "            5             "
echo "##########################" 
./nanotekspice and.nts < and5.txt
echo ""

echo "##########################"
echo "            6             "
echo "##########################" 
./nanotekspice and.nts < and6.txt
echo ""

echo "##########################"
echo "            7             "
echo "##########################" 
./nanotekspice and.nts < and7.txt
echo ""

echo "##########################"
echo "            8             "
echo "##########################" 
./nanotekspice and.nts < and8.txt
echo ""

echo "##########################"
echo "            9             "
echo "##########################" 
./nanotekspice and.nts < and9.txt
echo ""

echo "##########################"
echo "           10             "
echo "##########################" 
./nanotekspice and.nts < and10.txt
echo ""
